export default [
  {
    type:'slider',
    mainText: 'Реконструкція хрущовок, три нові мости та четверта гілка метро. Що у проєкті нового генплану Києва',
    secondText: 'КМДА презентувала новий генплан',
    imgPost: './img/gif12.gif',
    category: 'places',
    underCategory: 'fruits',
    views: 12126,
    comments: 1,
    data: '11:40 19.11.2019',
    isSuperProject: false,
  },
  {
    type:'image',
    mainText: ' «Ти так схудла!» Як не варто робити компліменти',
    secondText: 'Та коли вони недоречні',
    imgPost: './img/img2.jpg',
    category: 'business',
    underCategory: 'money',
    views: 20,
    comments: 0,
    data: '11:40 23.11.2019',
    isSuperProject: false,
  },
  {
    type:'image',
    mainText: 'Київ, який ви не помічаєте: дерева, заплави та парки, які є лише у нас',
    secondText: 'Про унікальні природні зони й оази нашого міста',
    imgPost: './img/img3.jpg',
    category: 'places',
    underCategory: 'city',
    views: 3222,
    comments: 3,
    data: '11:40 22.11.2019',
    isSuperProject: 'спецпроект',
    background: '#f3ca62'
  },
  {
    type:'image',
    mainText: 'Офісний простір Kooperativ від засновників Fedoriv і Bursa',
    secondText: 'Триповерховий коворкінг з амфітеатром і кавярнею біля Львівської площі',
    imgPost: './img/img4.jpg',
    category: 'places',
    underCategory: 'city',
    views: 40,
    comments: 0,
    data: '11:40 21.11.2019',
    isSuperProject: false,
  },
  {
    type:'image',
    mainText: 'Обери більш екологічну альтернативу: 6 побутових ситуацій',
    secondText: 'Читати книги чи дивитися відео? Тофу чи молочний сир?',
    imgPost: './img/img5.jpg',
    category: 'places',
    underCategory: 'village',
    views: 45,
    comments: 5,
    data: '11:40 21.11.2019',
    isSuperProject: 'спецпроект',
    background: '#fe6638'
  },
  {
    type:'image',
    mainText: 'Зберіть свій власний мікс морепродуктів з усього світу у ресторані Flagman 2019',
    secondText: 'Обирайте рибу разом із шеф-кухарем та спостерігайте за процесом',
    imgPost: './img/img56.jpg',
    category: 'eat',
    underCategory: 'meat',
    views: 224,
    comments: 6,
    data: '11:40 21.11.2019',
    isSuperProject: false,
  },
  {
    type:'slider',
    mainText: '80 закладів, які закрили чи перезапустили 2019 року в Києві',
    secondText: 'Закриття, перезапуски та переїзди',
    imgPost: './img/gif13.gif',
    category: 'eat',
    underCategory: 'fruits',
    views: 12126,
    comments: 7,
    data: '11:40 19.11.2019',
    isSuperProject: false,
  },
  {
    type:'image',
    mainText: '150 ресторанів і кафе, які відкрили 2019 року в Києві 2019',
    secondText: 'Усі нові ресторани, кафе та стритфуд міста',
    imgPost: './img/gif1.gif',
    category: 'eat',
    underCategory: 'restaurant',
    views: 5123,
    comments: 8,
    data: '11:40 20.11.2019',
    isSuperProject: false,
  },
  {
    type:'image',
    mainText: '«Стрибнемо в ліжечко?» і ще 99 способів запропонувати секс 2019',
    secondText: '«Про секс можна говорити серйозно, можна жартома, але головне – говорити»',
    imgPost: './img/gif2.gif',
    category: 'knowledge',
    underCategory: 'books',
    views: 64213,
    comments: 9,
    data: '11:40 19.11.2019',
    isSuperProject: false,
  },
  {
    type:'image',
    mainText: '50 барів, які відкрили 2019 року в Києві 2019',
    secondText: 'Усі заклади з коктейлями, вином і пивом, про які ми писали за рік',
    imgPost: './img/gif3.gif',
    category: 'eat',
    underCategory: 'fruits',
    views: 6515,
    comments: 10,
    data: '11:40 19.11.2019',
    isSuperProject: false,
  },
  {
    type:'image',
    mainText: '«Ти так схудла!» Як не варто робити компліменти 2019',
    secondText: 'Та коли вони недоречні',
    imgPost: './img/gif4.gif',
    category: 'business',
    underCategory: 'дилова етика',
    views: 2346,
    comments: 11,
    data: '11:40 19.11.2019',
    isSuperProject: false,
  },
  {
    type:'slider',
    mainText: '«Незручне питання»? Як говорити про підвищення зарплати 2019',
    secondText: '«Варто зрозуміти, скільки ви «коштуєте»',
    imgPost: './img/gif11.gif',
    category: 'business',
    underCategory: 'increase',
    views: 4126,
    comments: 12,
    data: '11:40 19.11.2019',
    isSuperProject: false,
  },
  {
    type:'slider',
    mainText: ' «Та ні, напевно»: як навчитися відмовляти людям 2019',
    secondText: '«Говорити «ні» – найцінніше вміння будь-якого професіонала»',
    imgPost: './img/gif14.gif',
    category: 'business',
    underCategory: 'money',
    views: 41260,
    comments: 0,
    data: '11:40 19.11.2019',
    isSuperProject: false,
  },
]